### ISSUE TITLE
Pas d'accès aux variables du templates

### ISSUE THREAD

**Issue by noirbizarre** [etalab/doc.data.gouv.fr#10]
La façon dont le template est importé aujourd'hui empêche la réutilisation de variables.
Impossible donc de référencer couleurs, espacements... proprement

**Comment by thimy** [comment]
Oui c'est un problème, on devait y réfléchir avant mon départ mais on n'a pas eu le temps, ce sera un des sujets pour la suite !

**Comment by noirbizarre** [comment]
ok :+1: 
(pour avoir maintenu un template comme ça pendant 2 ans, je pense que la bonne solution c'est de publier les assets sur npm pour pouvoir les importers proprement)
