### ISSUE TITLE
Gérer le netlify sur le compte etalab plutôt que Skeith918

### ISSUE THREAD

**Issue by noirbizarre** [etalab/doc.data.gouv.fr#11]
Le Netlify est aujourd'hui installé sur le compte `Skeith918` qui est du coup l'identité visible lors de l'authentification.
Par cohérence (et pour le côté rassurant pour certains), il serait mieux de le configurer sur le compte `etalab`

**Comment by noirbizarre** [comment]
Configuration de l'application OAuth sur github rajoutée: https://github.com/organizations/etalab/settings/applications/622554

**Comment by Skeith918** [comment]
L'authentification passe désormais par le compte etalab, les credentials de l'appli OAuth ont été injecter dans le serveur
