### ISSUE TITLE
Paramètre de fichier manquant pour l'endpoint /datasets/{dataset}/resources/{rid}/upload/

### ISSUE THREAD

**Issue by stevenkalwant** [etalab/doc.data.gouv.fr#119]
Bonjour,

J'ai l'impression qu'il manque le paramètre permettant d'envoyer le nouveau fichier pour la ressource voulue. 
En effet les 2 seuls paramètres de la méthode sont le rid et le dataset id, il n'y a pas de paramètre "file" de type formdata comme pour la méthode /datasets/{dataset}/upload/

Merci.

**Comment by maudetes** [comment]
En effet, dans la documentation automatique de l'api, il manque le paramètre fichier de la ressource sur cet endpoint.
En attendant une correction, je vous invite à regarder la documentation suivante: https://doc.data.gouv.fr/api/dataset-workflow/#remplacer-un-fichier-de-ressource

**Comment by stevenkalwant** [comment]
Bonjour,

Merci pour votre réponse
