### ISSUE TITLE
Redesign de plusieurs pages du site

### ISSUE THREAD

**Issue by bboulesteix** [etalab/doc.data.gouv.fr#59]
Cette _issue_ présente des propositions de design pour les types de pages suivants :

1. Page d’accueil : celle sur laquelle on arrive quand on visite `doc.data.gouv.fr` ;
2. Page catégorie (à créer) : la page qui présentera tous les articles d’une même section ;
3. Page article : l’unité de base de la documentation, la page qui présente le contenu d’un article ;
4. Page de résultats de recherche (à créer) : la page qui affichera les résultats de recherche.

**NB** : la page catégorie servira d’étage intermédiaire entre la page d’accueil et la page article. Voir le gif ci-dessous. 👇 

![flow-navigation-documentation](https://user-images.githubusercontent.com/3286488/49449551-6b022000-f7db-11e8-9b6b-b0cf428f3358.gif)

Les images ci-dessous ont été produites dans l’application [Sketch](https://sketchapp.com). Si vous avez un compte [Sketch Cloud](https://sketch.cloud), envoyez-moi l’adresse e-mail qui y est associée. Sketch Cloud vous permettra de commenter les images. Vos commentaires peuvent aussi bien être publiés ici, en réponse à cette _issue_. C’est à votre convenance. 🤷‍♂️ 

## Page d’accueil

![1 accueil 1140px](https://user-images.githubusercontent.com/3286488/49450281-f7f9a900-f7dc-11e8-9e3b-e129082f33bf.png)

## Page catégorie

![2 categorie 1140px](https://user-images.githubusercontent.com/3286488/49451238-05179780-f7df-11e8-8cf2-d365a4f741e3.png)

## Page article

![3 article 960px](https://user-images.githubusercontent.com/3286488/50777818-e2284980-129c-11e9-902c-0a573d7e25f4.png)

## Page de résultats de recherche

![4 recherche 1140px](https://user-images.githubusercontent.com/3286488/49451252-0fd22c80-f7df-11e8-9f7c-a160addadd74.png)

## Choses à faire

- [ ] Créer un _layout_ dans Jekyll pour la page catégorie
- [x] Ajouter le _plugin_ [simple-Jekyll-Search](https://github.com/christian-fei/Simple-Jekyll-Search) au site (pour la recherche)
- [ ] Créer un _layout_ dans Jekyll pour la page des résultats de recherche
- [ ] Modifier le _layout_ de la page article
- [ ] Modifier le _layout_ de la page d’accueil

**Comment by taniki** [comment]
@bboulesteix tu gardes ce chantier ouvert ? Je pense qu'on peut y aller itérativement en commencant par la page d'accueil de la documentation (cf https://github.com/etalab/doc.data.gouv.fr/issues/83)
