### ISSUE TITLE
Ajouter un lien direct pour la modification dans github

### ISSUE THREAD

**Issue by noirbizarre** [etalab/doc.data.gouv.fr#6]
La version embarquée data data.gouv.fr incluait un lien directe pour la modification dans pages dans github. Les seules contributions à la FAQ ont été faites par ce lien et il sert encore (cf. etalab/data.gouv.fr#45). Je pense qu'il serait bien de le remettre sur cette version.

![screenshot-www data gouv fr-2017-12-14-19-18-19-426](https://user-images.githubusercontent.com/15725/34007963-139c1648-e104-11e7-925a-40237586e612.png)

**Comment by thimy** [comment]
Bonne idée ! Tu saurais me dire vers quoi ça redirigeait exactement ?

**Comment by noirbizarre** [comment]
Yep, ça dirigeais vers la page d'édition github.
Ex: https://doc.data.gouv.fr/faq/citoyen.html doit pointer vers https://github.com/etalab/doc.data.gouv.fr/edit/master/_faq/citoyen.md

Par contre je me pose une question: est-ce qu'on dirige vers la page d'édition github ou la page d'édition dans l'admin (https://doc.data.gouv.fr/admin/#/collections/faq/entries/citoyen) ?
