### ISSUE TITLE
Ajouter des liens entre les articles de la documentation

### ISSUE THREAD

**Issue by loichay** [etalab/doc.data.gouv.fr#64]
Il peut être pertinent de compléter les contenus de certains paragraphes et/ou de créer des liens vers les contenus d'autres articles. Par exemple, [créer une organisation/à faire ensuite](https://doc.data.gouv.fr/organisations/creer-une-organisation/#%C3%80-faire-ensuite) pourrait être complété par le point _effectuer une demande de certification pour obtenir et attacher le badge "service public certifié" à votre organisation_ et relié à [faq/producteur/les services publics certifiés](https://doc.data.gouv.fr/faq/producteur/#les-services-publics-certifi%C3%A9s).

**Comment by bboulesteix** [comment]
Ça me semble être une excellente idée, vous avez raison. Merci bien. J’ajoute l’idée dans #59 et ferme ce ticket pour éviter les doublons.
