### ISSUE TITLE
Expliciter les secrets qui empêchent la publication de données

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/doc.data.gouv.fr#65]
[Cette page](https://doc.data.gouv.fr/a-propos/que-publier-et-comment-le-publier/), dans [ce fichier](https://github.com/etalab/doc.data.gouv.fr/blob/master/articles/_a-propos/que-publier-et-comment-le-publier.md), mentionne plusieurs fois le concept de *secrets*.

Il me semblent que les 2 articles traitant de ces sujets dans le CRPA sont :
- [L'article 311-5](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000031366350&idArticle=LEGIARTI000031367708)
- [L'article 311-6](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000031366350&idArticle=LEGIARTI000033218964)

Comment mieux les expliquer ? Au moins les référencer ? Faut-il mentionner d'autres choses ?

**Comment by bboulesteix** [comment]
> Comment mieux les expliquer ?

Pas en pointant vers les articles du _Code des relations entre le public et l'administration_, à mon avis. 🙂 En revanche, je pense que nous pourrions rediriger les lecteurs curieux vers la page [sur laquelle la CADA détaille les différents secrets protégés par la loi](https://www.cada.fr/particulier/les-secrets-proteges-par-la-loi).
