### ISSUE TITLE
Lien d'édition des pages non valide

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/doc.data.gouv.fr#66]
Le lien d'édition des pages n'est pas valide car les articles sont dans une collection :
https://github.com/etalab/doc.data.gouv.fr/blob/fb58f5c6acbb36018422a58c4c4d720ffb2ebae7/_config.yml#L32

Actuellement, le lien pour éditer un fichier ne prend pas en compte cette collection, ce qui donne une 404 sur GitHub.

## Reproduction

1. Aller sur https://doc.data.gouv.fr/faq/citoyen/
2. Cliquer sur le bouton Éditer cette page en base de page
3. Être redirigé vers https://github.com/etalab/doc.data.gouv.fr/edit/master/_faq/citoyen.md et non https://github.com/etalab/doc.data.gouv.fr/edit/master/articles/_faq/citoyen.md

**Comment by AntoineAugusti** [comment]
Fixé une fois que https://github.com/etalab/template-jekyll/pull/11 sera mergé et le thème mis à jour ici

**Comment by bboulesteix** [comment]
Merci @AntoineAugusti. Je vois que https://github.com/etalab/template-jekyll/pull/11 et  https://github.com/etalab/template-jekyll/pull/12 ont été _mergées_. Je ferme donc ce ticket.

**Comment by AntoineAugusti** [comment]
Il manque encore l'upgrade de la gem à faire ici @bboulesteix. Les fixs ont été mergé mais une nouvelle versin du template n'a pas été sortie et il faudra faire l'upgrade ici
