### ISSUE TITLE
Support pédagogiques open data 

### ISSUE THREAD

**Issue by romtal** [etalab/doc.data.gouv.fr#67]
La commission européenne a créé une série de modules e-learning sur l'open data.
Ces derniers ont été réalisé par l'ODI et sont sous CCby SA.
Laure souhaiterait récupérer ce travail et lui donner de la visibilité sur data.gouv.fr.
Un exemple d'intégration sur le portail open data Irlandais : https://data.gov.ie/edpelearning/fr/#/id/co-01

**Comment by abulte** [comment]
C'est cool 👍 Il faut quand même lire tout ça voir s'il n'y a pas de contradiction avec ce qu'on raconte d'habitude (peut-être un petit sujet licence avec la CC qui est poussée ? Mais il parlent aussi de LO).

Je verrais bien (et/ou) :
- un renvoi vers cet outil (dont hébergerait une copie sur un sous domaine de data.gouv.fr ou sous répertoire de doc.data.gouv.fr) depuis doc.data.gouv.fr
- développer le menu "Découvrez l'open data" sur data.gouv.fr avec une entrée vers la doc et vers ces contenus

**Comment by abulte** [comment]
Les sources ont l'air d'être ici : https://github.com/theodi/ODI-eLearning

**Comment by bboulesteix** [comment]
Si l’on envisage [doc.data.gouv.fr](http://doc.data.gouv.fr/) comme un manuel d’utilisation de [data.gouv.fr](https://www.data.gouv.fr/fr/), alors les cours en ligne de l’ODI n’y ont pas leur place. Bien qu’ils soient très intéressants, les cours sont trop généralistes, pas suffisamment en lien avec les fonctionnalités proposées par [data.gouv.fr](https://www.data.gouv.fr/fr/), à mon avis.

Où parler des cours de l’ODI alors ? Je ne sais pas. 

Deux idées :

1. Si nous tenons _vraiment_ à ce que les cours figurent sur [doc.data.gouv.fr](http://doc.data.gouv.fr/), nous pourrions consacrer un article aux ressources utiles, ou aux références intéressantes — avec le risque que cet article se transforme à terme en fourre-tout sans queue ni tête.
2. Pour satisfaire l’exigence de Laure, nous pourrions pointer vers le cours en ligne de l’ODI (https://www.europeandataportal.eu/elearning/en/#/id/co-01) depuis le pied de page de [data.gouv.fr](https://www.data.gouv.fr/fr/), par exemple en ajoutant un lien dans la colonne **L’Open Data**, la première en partant de la gauche.

![Screenshot_2019-06-24 Accueil - data gouv fr](https://user-images.githubusercontent.com/3286488/60019996-5f028080-968f-11e9-83b1-aef5762e763e.png)
