### ISSUE TITLE
Passage de doc.data.gouv.fr à data.gouv.fr

### ISSUE THREAD

**Issue by noirbizarre** [etalab/doc.data.gouv.fr#7]
cf. etalab/udata-gouvfr#242 :

> Il est impossible de passer de doc.data.gouv.fr à www.data.gouv.fr en cliquant en haut à gauche de la page sur le logo data.gouv.fr qui renvoie vers doc.data.gouv.fr 

Les modalités (clic sur le logo en haut ou autre...) sont à discuter/définir

**Comment by taniki** [comment]
Il y a maintenant un lien discret "revenir vers data.gouv.fr" dans le menu (:
