### ISSUE TITLE
Page producteur

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/doc.data.gouv.fr#71]
La page https://doc.data.gouv.fr/faq/producteur/ rencontre plusieurs problèmes :
- Des liens ne sont pas présents, alors que la syntaxe Markdown semble adaptée. C'est par exemple le cas vers `legifrance-producer`
- Des listes numérotées ont un rendu non approprié, uniquement sur le site web et pas en Markdown, comme par exemple `Les données thématiques telles que:` (préfixé par un 1. et non 3.)

**Comment by noirbizarre** [comment]
Bonjour,

La documentation est en cours de réécriture cf. https://github.com/etalab/doc.data.gouv.fr/pull/70

Concernant les listes à puces. La syntaxe markdown ne prend pas en compte le chiffre dans le rendu, il est possible d'écrire une liste complète où toutes les entrées commencent par 1., elle serait quand même rendu numérotée. L’intérêt, en sachant que c'est une liste numérotée, est de pouvoir réordonner les entrées sans avoir à les renuméroter à la main. L'objectif, même si le markdown est joliment présenté par github, est vraiment d'être rendu dans la doc.

**ex:**
1. puce numérotée 1
1. puce aussi numérotée 1
42. puce numérotée 42

Même si les nombres des puces ne sont pas les bons, quand tu lis ce commentaire, tu ne vois que le rendu qui lui est correcte :wink:

**Comment by bboulesteix** [comment]
La page en question est une page « historique », qui est vouée à disparaitre (voir #70). Tu as raison @AntoineAugusti, la page _Producteur_ est perfectible, mais plutôt que de la refondre, je préfère la supprimer et m’en servir pour enrichir les articles qui sont déjà en ligne. Je ne crois pas que les pages publiés dernièrement (voir #36) souffrent des problèmes de Markdown que tu soulignes. Je ferme donc ce ticket. 👋
