### ISSUE TITLE
Modification contenu "Associer une réutilisation à un jeu de données"

### ISSUE THREAD

**Issue by mathildehg** [etalab/doc.data.gouv.fr#73]
Hello, 

Il pourrait être intéressant de modifier le contenu de la page https://doc.data.gouv.fr/reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees/

**Texte actuel:** 

> Référencer une réutilisation sur la page d’un jeu de données ne prend que quelques secondes et permet de :
>     donner de la visibilité à la réutilisation ;
>     montrer à quoi le jeu de données peut servir ;
>     inspirer d’autres réutilisations potentielles ;
>     remercier le producteur des données réutilisées.

**Notre proposition de modification:** 
Référencer une réutilisation sur la page d’un jeu de données ne prend que quelques secondes et permet de :
- donner de la visibilité à la réutilisation et/ou au projet que vous portez ;
- montrer le potentiel de réutilisation du jeu de données ;
- inspirer d'autres réutilisations potentielles ;
- engager un dialogue avec le producteur du jeu de données. 

A dispo pour en parler ! 
Mathilde

**Comment by bboulesteix** [comment]
Bonjour @mathildehg, merci pour votre proposition.

J’ai légèrement modifié ce que vous proposiez, pour arriver à la liste suivante :

> Référencer une réutilisation sur la page d’un jeu de données permet de :
> - donner de la visibilité à la réutilisation et au projet dans lequel elle s’inscrit ;
> - montrer à d’autres personnes comment le jeu de données peut être réutilisé ;
> - donner des idées et inspirer d'autres réutilisations potentielles ;
> - engager un dialogue avec le producteur du jeu de données.

Si ma proposition vous convient, je peux ensuite changer le texte de mon côté sur doc.data.gouv.fr.

**Comment by mathildehg** [comment]
Bonjour @bboulesteix,

Merci pour ta réponse. Tes modifications sont très pertinentes. On peut changer le texte dans ce sens :)

**Comment by bboulesteix** [comment]
Allons-y alors. 🚀
